### ISSUE TITLE
Failed reading config file error

### ISSUE THREAD

**Issue by AugustasV** [gsilvapt/pmz#30]
I would like to use this tool, but getting Failed reading onfig file error
```➜  bin pmz new
ERROR: 2022/01/12 21:12:20 /home/namai/go/pkg/mod/github.com/gsilvapt/pmz@v0.0.0-20211118182444-62441c11945a/internal/logs/logger.go:45: Failed reading config file: 
➜  bin pmz -v    
pmz version 0.3
➜  bin pmz update
ERROR: 2022/01/12 21:12:35 /home/namai/go/pkg/mod/github.com/gsilvapt/pmz@v0.0.0-20211118182444-62441c11945a/internal/logs/logger.go:45: Failed reading config file: ```

**Comment by gsilvapt** [comment]
Hello @AugustasV :wave:

Thank you so much for your interest in using `pmz`. Super excited to see others using this 🤩  
I don't want to ask you to publish here you config for security reasons, but to have `update` command working you should have `gitrepo`, `gituser` and `repotoken` variables defined in your configuration file (Should be in `~/.pmz.yaml` or if you change it to some other location you will need to specify it).

Let me know if you have those and they are valid. Maybe the issue is elsewhere. 

Thanks again 🙇

**Comment by AugustasV** [comment]
thank you for tips, updated my .pmz.yaml file but getting that kind of error, why is that?
```
augustasv@augustasv-ProBook:~/Documents/zet$ pmz new
ERROR: 2022/01/16 09:45:24 /home/augustasv/go/pkg/mod/github.com/gsilvapt/pmz@v0.0.0-20211118182444-62441c11945a/internal/logs/logger.go:45: failed to create directory: mkdir /home/namai/zet/20220116094524: no such file or directory
```

**Comment by AugustasV** [comment]
```
augustasv@augustasv-ProBook:~/Documents/zet$ pmz update
INFO: 2022/01/16 11:14:18 repository already up to date
augustasv@augustasv-ProBook:~/Documents/zet$ pmz save
ERROR: 2022/01/16 11:14:20 /home/augustasv/go/pkg/mod/github.com/gsilvapt/pmz@v0.0.0-20211118182444-62441c11945a/internal/logs/logger.go:45: failed committing changes: 
 author field is required
```
That's weird, why is that? ssh key added. But I see that even after pmz update my token was not used.

**Comment by gsilvapt** [comment]
Did it solve your problems, @AugustasV ? Do you need any further support?
Again, thank you very much for using `pmz`. Excited to read your feedback! 😄

**Comment by AugustasV** [comment]
So far so good, but commit message all the time is 
updating your zettelkasten
during `pmz new --title test` I was expecting that commit message would be different.

**Comment by gsilvapt** [comment]
Hum, that is a valid feature, absolutely. I will try to find time to develop a feature to edit the commit message. Something like `pmz save --message "<my message>"`, else it will default to that message. How does that look like?

**Comment by AugustasV** [comment]
Thank you, created an separate issue. #31 
Closing this one.
