### ISSUE TITLE
bug: `pmz new --title` with a full strings errors out

### ISSUE THREAD

**Issue by gsilvapt** [gsilvapt/pmz#9]
When creating a new note and using the `title` flag, a full string fails.

**Comment by acagastya** [comment]
I tried this with the latest code, and it seems to be opening the editor and prefillling it with
```md
# lorem ipsum

# Summary


# Notes


```

Is that not expected behaviour?  If not, can you please describe, so I might have a look into it?

**Comment by gsilvapt** [comment]
Hey!

Yes, I forgot to add I fixed this. Thanks!
